resources:
  - name: S_Bash_0436_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: art_v
      pattern: "*"


pipelines:
  - name: FileSpec_Pipeline_6
    steps:
      - name: S_Bash_0436
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0436_FileSpec
        execution:
          onExecute:
            - echo "executing step..."
            - ls
