resources:
  - name: Get_Files
    type: FileSpec
    configuration:
      sourceArtifactory: ACMEArt
      aql: "{'repo': 'acme-docker-local'}"
    
pipelines:
  - name: PropertyDemo
    configuration:
      jfrogCliVersion: 2  
    steps:
      - name: ArtifactoryFiles
        type: Bash
        configuration:
          inputResources:
            - name: Get_Files
        execution:
          onExecute:
            - cat $HOME/.jfrog/logs/jfrog-cli*
            - ls
