resources:
  - name: Image_2
    type: Image
    configuration:
      registry: ACMEArt
      sourceRepository: acme-docker-staging-local
      imageName: ubuntu
      imageTag: latest

pipelines:
  - name: Image_Pipeline
    configuration:
      jfrogCliVersion: 2   
    steps:
      - name: step_IMAGE_2
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: Image_2
        execution:
          onExecute:
            - write-output "executing step..."
