resources:
  - name: MyIncomingWebhookResource
    type: IncomingWebhook
    configuration:
      webhookName: ACMEIncomingWebhook

pipelines:
  - name: IncomingWebhookResource_Pipeline
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        inputResources:
          - name: MyIncomingWebhookResource
      execution:
          onExecute:
            - echo "$res_MyIncomingWebhookResource_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"
