resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minutes
      
  - name: gitrepo_trigger
    type: GitRepo
    configuration:
      gitProvider: ACMEGit
      path: RjSH1/jfrog-pipelines-resources-examples      

pipelines:      
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: gitrepo_trigger
              trigger: false
            - name: cron_trigger
              trigger: false
        execution:
          onExecute:
            - printenv
