resources:
  - name: Get_File
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      aql: "{'repo': 'docker-local'}"
    
pipelines:
  - name: PropertyDemo_1
    steps:
      - name: ArtifactoryFiles
        type: Bash
        configuration:
          inputResources:
            - name: Get_File
        execution:
          onExecute:
            - cat $HOME/.jfrog/logs/jfrog-cli*
            - ls
